import requests
import json
from time import sleep
from util.login import login


if __name__ == '__main__':
    session = login()
    teams = [
        {'cn': "", 'en': "Flyer_3", 'members': [0, 1, 2]},
        {'cn': "", 'en': "L3", 'members': [0, 3, 2]},
        {'cn': "", 'en': "Z303", 'members': [0, 4, 2]},
        {'cn': "", 'en': "Goo", 'members': [5, 6, 1]},
        {'cn': "", 'en': "Rivercrab", 'members': [0, 7, 2]},
        {'cn': "", 'en': "PSX", 'members': [5, 8, 9]},
        {'cn': "", 'en': "3K", 'members': [10, 11, 12]},
        {'cn': "", 'en': "XGF", 'members': [13, 14, 15]},
        {'cn': "", 'en': "miyoshi gakusei", 'members': [16, 17, 18]},
        {'cn': "", 'en': "a team", 'members': [19, 6, 20]},
        {'cn': "", 'en': "RP overflow", 'members': [6, 20, 2]},
        {'cn': "", 'en': "Reloaded", 'members': [14, 9, 8]},
        {'cn': "", 'en': "acm.buaa.edu.cn", 'members': [0, 7, 5]},
        {'cn': "", 'en': "DDR3", 'members': [21, 22, 23]},
        {'cn': "", 'en': "Happiness-ACK", 'members': [8, 20, 18]},
        {'cn': "", 'en': "Phenom", 'members': [24, 25, 15]},
        {'cn': "", 'en': "RiverCrab", 'members': [0, 7, 2]},
        {'cn': "", 'en': "From Beijing With Love", 'members': [16, 9, 19]},
        {'cn': "", 'en': "DDR4", 'members': [23, 21, 26]},
        {'cn': "", 'en': "BBS", 'members': [14, 19, 13]},
        {'cn': "", 'en': "Minerva", 'members': [27, 28, 29]},
        {'cn': "", 'en': "Regulus", 'members': [30, 9, 2]},
        {'cn': "", 'en': "Admin", 'members': [31, 32, 33]},
        {'cn': "", 'en': "None", 'members': [34, 35, 36]},
        {'cn': "", 'en': "Freedom", 'members': [10, 27, 37]},
        {'cn': "", 'en': "sjz330", 'members': [38, 39, 40]},
        {'cn': "", 'en': "Bianchengla", 'members': [33, 41, 42]},
        {'cn': "", 'en': "WhrsMyPenny", 'members': [43, 44, 45]},
        {'cn': "", 'en': "passerby", 'members': [28, 29, 46]},
        {'cn': "", 'en': "EverAC", 'members': [47, 48, 49]},
        {'cn': "", 'en': "BUAA4294967295", 'members': [33, 41, 49]},
        {'cn': "", 'en': "WeLikeBalloons", 'members': [50, 51, 52]},
        {'cn': "", 'en': "KeepItSimpleStupid", 'members': [53, 54, 55]},
        {'cn': "", 'en': "ZeroSix", 'members': [56, 57, 58]},
        {'cn': "", 'en': "OhMyGold", 'members': [38, 59, 40]},
        {'cn': "", 'en': "plum*", 'members': [33, 38, 41]},
        {'cn': "", 'en': "htc", 'members': [60, 61, 62]},
        {'cn': "", 'en': "Bella", 'members': [54, 53, 59]},
        {'cn': "", 'en': "WeLikeBalloons", 'members': [50, 51, 52]},
        {'cn': "", 'en': "Balloons", 'members': [63, 64, 65]},
        {'cn': "", 'en': "LittleBusters", 'members': [66, 67, 68]},
        {'cn': "", 'en': "Railgun Force", 'members': [69, 70, 71]},
        {'cn': "", 'en': "Buaa_Goal", 'members': [72, 73, 74]},
        {'cn': "", 'en': "LittleBusters", 'members': [68, 67, 75]},
        {'cn': "", 'en': "RockMan", 'members': [76, 77, 78]},
        {'cn': "", 'en': "Phasianus", 'members': [53, 50, 79]},
        {'cn': "", 'en': "CTH", 'members': [60, 61, 62]},
        {'cn': "", 'en': "LWL", 'members': [80, 81, 82]},
        {'cn': "", 'en': "Oracle", 'members': [83, 81, 84]},
        {'cn': "", 'en': "Hentai Spirit", 'members': [66, 68, 75]},
        {'cn': "", 'en': "TheWaySoFar", 'members': [79, 85, 86]},
        {'cn': "", 'en': "Damocles", 'members': [76, 77, 72]},
        {'cn': "", 'en': "Zero Limit", 'members': [87, 88, 89]},
        {'cn': "", 'en': "Trine", 'members': [90, 82, 91]},
        {'cn': "", 'en': "Theme of SSS", 'members': [92, 93, 94]},
        {'cn': "", 'en': "I-PPPei", 'members': [95, 96, 97]},
        {'cn': "", 'en': "TDL", 'members': [88, 98, 99]},
        {'cn': "", 'en': "Prometheus", 'members': [100, 101, 102]},
        {'cn': "", 'en': "NewBeer", 'members': [103, 104, 105]},
        {'cn': "", 'en': "TheWaySoFar", 'members': [79, 85, 86]},
        {'cn': "", 'en': "Null", 'members': [106, 107, 108]},
        {'cn': "", 'en': "undetermined", 'members': [84, 81, 75]},
        {'cn': "", 'en': "LovelyDonuts", 'members': [109, 110, 111]},
        {'cn': "", 'en': "Damocles", 'members': [76, 77, 72]},
        {'cn': "", 'en': "TheThreeMusketeers", 'members': [112, 113, 114]},
        {'cn': "", 'en': "TDL", 'members': [88, 98, 115]},
        {'cn': "", 'en': "Null", 'members': [106, 107, 108]},
        {'cn': "", 'en': "ResuscitatedHope", 'members': [116, 117, 118]},
        {'cn': "", 'en': "GG", 'members': [119, 120, 121]},
        {'cn': "", 'en': "LovelyDonuts", 'members': [109, 110, 111]},
        {'cn': "", 'en': "ACMakeMeHappier", 'members': [112, 113, 114]},
        {'cn': "", 'en': "QAQ", 'members': [122, 123, 124]},
        {'cn': "", 'en': "deticxe", 'members': [103, 105, 104]},
        {'cn': "", 'en': "stO Orz", 'members': [125, 126, 127]},
        {'cn': "黑人问号.jpg", 'en': "Three Investigators", 'members': [98, 106, 115]},
        {'cn': "TAT", 'en': "Ascender", 'members': [122, 124, 128]},
        {'cn': "复苏", 'en': "ResuscitatedHope", 'members': [116, 117, 118]},
        {'cn': "我需要治疗", 'en': "Heynihao", 'members': [129, 130, 131]},
        {'cn': "CE使我快乐", 'en': "ACMakeMeHappier", 'members': [112, 132, 114]},
        {'cn': "人生已经如此的艰难", 'en': "L.I.P", 'members': [133, 134, 135]},
        {'cn': "极值点", 'en': "TooFarTooClose", 'members': [136, 137, 138]},
        {'cn': "我们吓成一团了", 'en': "stO Orz", 'members': [125, 126, 127]},
        {'cn': "水能载舟", 'en': "deticxe", 'members': [105, 104, 111]},
        {'cn': "头文件", 'en': "#include", 'members': [139, 140, 141]},
        {'cn': "tvcr", 'en': "tvcr", 'members': [142, 121, 143]},
        {'cn': "", 'en': "The South China Sea", 'members': [133, 134, 135]},
        {'cn': "趣味时光", 'en': "Nonsense Time", 'members': [129, 130, 131]},
        {'cn': "小黄鸡咕咕咕", 'en': "Ascender", 'members': [122, 124, 128]},
        {'cn': "啊，队友呢？队友呢？队友呢？！队友呢？！？！", 'en': "Eh,gugugu?Gugugu?Gugugu?!Gugugu?!?!", 'members': [116, 117, 118]},
        {'cn': "比宇宙更远的地方", 'en': "TooFarTooClose", 'members': [136, 137, 138]},
        {'cn': "除了AC", 'en': "WithoutAC", 'members': [134, 142, 144]},
        {'cn': "从不刷题队", 'en': "zhenxiang", 'members': [139, 140, 141]},
        {'cn': "梦中做自己", 'en': "ForTheDream", 'members': [133, 135, 145]},
        {'cn': "菜里别加鎕", 'en': "No CE in vegetable", 'members': [146, 147, 148]},
        {'cn': "除了AC", 'en': "WithoutAC", 'members': [134, 142, 138]},
        {'cn': "咕咕鸽", 'en': "Tranquility", 'members': [129, 130, 131]},
        {'cn': "打不赢电脑", 'en': "Knocked out by AI", 'members': [134, 144, 149]},
        {'cn': "你好，世界", 'en': "Hello, world", 'members': [137, 138, 150]},
        {'cn': "无限大の梦", 'en': "Butter_Fly", 'members': [135, 145, 151]},
        {'cn': "我裂开了", 'en': "We Gathered", 'members': [146, 147, 148]},
        {'cn': "试炼者", 'en': "Alchemist", 'members': [152, 153, 154]},
        {'cn': "试炼者", 'en': "tsimehclA", 'members': [152, 153, 154]},
        {'cn': "一号位", 'en': "fishing", 'members': [155, 156, 157]},
        {'cn': "萌新求带", 'en': "freshmanAirProPlus", 'members': [158, 159, 160]},
        {'cn': "CE：从爆零开始的ACM生活", 'en': "CE: ACM Life From Zero", 'members': [161, 162, 163]},
        {'cn': "差点一打三", 'en': "Actually 1V3", 'members': [164, 165, 166]},
        {'cn': "将来我一定比你聪明比你强", 'en': "Wangzai Milk", 'members': [167, 168, 169]},
    ]

    regions = {
        "2019": [
            { 'type': 1, 'region': "银川赛区（宁夏理工学院）", 'honor': [[102, 4], [103, 4], [104, 5], [105, 5]] },
            { 'type': 1, 'region': "南京赛区（南京航空航天大学）", 'honor': [[95, 4], [96, 4], [99, 6]] },
            { 'type': 1, 'region': "徐州赛区（中国矿业大学）", 'honor': [[101, 4], [102, 4], [103, 5]] },
            { 'type': 1, 'region': "南昌赛区（江西师范大学）", 'honor': [[97, 4], [96, 5], [98, 5]] },
            { 'type': 1, 'region': "沈阳赛区（东北大学）", 'honor': [[100, 5], [99, 6]] },
            { 'type': 1, 'region': "上海赛区（上海大学）", 'honor': [[95, 4], [97, 4], [98, 5]] },
            { 'type': 1, 'region': "EC-Final（西北工业大学）", 'honor': [[97, 4], [95, 5], [100, 5], [102, 5], [96, 6]] },
            { 'type': 2, 'region': "CCPC秦皇岛赛区（东北大学秦皇岛分校）", 'honor': [[99, 5]] },
            { 'type': 2, 'region': "CCPC哈尔滨赛区（东北林业大学）", 'honor': [[97, 4], [96, 5]] },
            { 'type': 2, 'region': "CCPC厦门赛区（厦门理工学院）", 'honor': [[95, 4], [98, 5], [106, 6]] },
            { 'type': 2, 'region': "CCPC-Final（中国传媒大学）", 'honor': [[95, 5]] },
        ],
        "2018": [
            { 'type': 0, 'region': "波尔图，葡萄牙", 'honor': [[86, -21]] },
            { 'type': 1, 'region': "南京赛区（南京航空航天大学）", 'honor': [[90, 4], [89, 5], [88, 5]] },
            { 'type': 1, 'region': "沈阳赛区（东北大学）", 'honor': [[87, 4], [86, 4]] },
            { 'type': 1, 'region': "徐州赛区（中国矿业大学）", 'honor': [[90, 4], [89, 5], [91, 5]] },
            { 'type': 1, 'region': "青岛赛区（中国石油大学）", 'honor': [[86, 4], [91, 5]] },
            { 'type': 1, 'region': "北京赛区（北京大学）", 'honor': [[92, 5], [93, 6]] },
            { 'type': 1, 'region': "焦作赛区（河南理工大学）", 'honor': [[87, 4], [92, 5], [88, 6], [93, 6]] },
            { 'type': 1, 'region': "EC-Final（西北工业大学）", 'honor': [[87, 4], [86, 4], [89, 4], [90, 4], [92, 5]] },
            { 'type': 2, 'region': "CCPC吉林赛区（北华大学）", 'honor': [[94, 4], [91, 4]] },
            { 'type': 2, 'region': "CCPC秦皇岛赛区（东北大学秦皇岛分校）", 'honor': [[89, 4], [88, 4]] },
            { 'type': 2, 'region': "CCPC桂林赛区（桂林电子科技大学）", 'honor': [[86, 4], [87, 4]] },
            { 'type': 2, 'region': "CCPC-Final（哈尔滨工业大学深圳）", 'honor': [[86, 5], [94, 6]] },
        ],
        "2017": [
            { 'type': 0, 'region': "北京，中国", 'honor': [[74, -14]] },
            { 'type': 1, 'region': "沈阳赛区（东北大学）", 'honor': [[74, 2], [75, 4]] },
            { 'type': 1, 'region': "西安赛区（西北工业大学）", 'honor': [[74, 4], [76, 4], [77, 4]] },
            { 'type': 1, 'region': "青岛赛区（中国石油大学）", 'honor': [[77, 4], [78, 6]] },
            { 'type': 1, 'region': "北京赛区（北京大学）", 'honor': [[79, 5], [80, 5], [81, 6]] },
            { 'type': 1, 'region': "香港赛区（香港科技大学）", 'honor': [[76, 5]] },
            { 'type': 1, 'region': "南宁赛区（广西大学）", 'honor': [[75, 4], [78, 4], [82, 4], [83, 6]] },
            { 'type': 1, 'region': "乌鲁木齐赛区（新疆大学）", 'honor': [[84, 5]] },
            { 'type': 1, 'region': "ECL-Final（上海大学）", 'honor': [[74, 3], [75, 5], [77, 5], [82, 5]] },
            { 'type': 2, 'region': "CCPC哈尔滨赛区（哈尔滨理工大学）", 'honor': [[77, 4], [76, 4]] },
            { 'type': 2, 'region': "CCPC秦皇岛赛区（东北大学秦皇岛分校）", 'honor': [[78, 4], [79, 5], [83, 6]] },
            { 'type': 2, 'region': "CCPC杭州赛区（浙江理工大学）", 'honor': [[74, 4], [75, 5], [82, 5]] },
            { 'type': 2, 'region': "CCPC-Final（哈尔滨工业大学）", 'honor': [[74, 4]] },
        ],
        "2016": [
            { 'type': 0, 'region': "拉皮德城，美国", 'honor': [[65, -56]] },
            { 'type': 1, 'region': "大连赛区（大连海事大学）", 'honor': [[65, 2], [66, 4], [67, 6]] },
            { 'type': 1, 'region': "沈阳赛区（东北大学）", 'honor': [[68, 5], [69, 5], [70, 6]] },
            { 'type': 1, 'region': "香港赛区（香港中文大学）", 'honor': [[71, 6], [85, 7]] },
            { 'type': 1, 'region': "青岛赛区（中国石油大学）", 'honor': [[65, 4], [69, 5], [66, 6]] },
            { 'type': 1, 'region': "北京赛区（北京大学）", 'honor': [[72, 5], [70, 6], [73, 7]] },
            { 'type': 1, 'region': "China-Final（上海大学)", 'honor': [[65, 4], [70, 5], [72, 5], [66, 5]] },
            { 'type': 2, 'region': "CCPC长春赛区（吉林大学）", 'honor': [[65, 4], [66, 6]] },
            { 'type': 2, 'region': "CCPC合肥赛区（安徽大学）", 'honor': [[72, 5], [69, 5]] },
            { 'type': 2, 'region': "CCPC杭州赛区（杭州电子科技大学）", 'honor': [[70, 4], [67, 4], [73, 5]] },
            { 'type': 2, 'region': "CCPC-Final（宁波理工学院）", 'honor': [[65, 5], [66, 5]] },
        ],
        "2015": [
            { 'type': 0, 'region': "普吉，泰国", 'honor': [[59, -14]] },
            { 'type': 1, 'region': "长春赛区（东北师范大学）", 'honor': [[56, 5], [57, 6], [58, 6]] },
            { 'type': 1, 'region': "沈阳赛区（东北大学）", 'honor': [[59, 1], [60, 5]] },
            { 'type': 1, 'region': "合肥赛区（中国科学技术大学）", 'honor': [[56, 5], [61, 5]] },
            { 'type': 1, 'region': "北京赛区（北京大学）", 'honor': [[62, 6], [63, 6]] },
            { 'type': 1, 'region': "上海赛区（华东理工大学）", 'honor': [[63, 5], [64, 5]] },
            { 'type': 1, 'region': "EC-Final（上海大学）", 'honor': [[59, 3], [61, 4], [56, 4], [63, 6]] },
            { 'type': 2, 'region': "CCPC南阳赛区（南阳理工学院）", 'honor': [[59, 2], [60, 5], [62, 5]] },
        ],
        "2014": [
            { 'type': 0, 'region': "马拉喀什，摩洛哥", 'honor': [[50, -28]] },
            { 'type': 1, 'region': "牡丹江赛区（牡丹江师范学院）", 'honor': [[48, 4], [49, 5]] },
            { 'type': 1, 'region': "鞍山赛区（辽宁科技大学）", 'honor': [[50, 3], [51, 5], [52, 6]] },
            { 'type': 1, 'region': "西安赛区（西北工业大学）", 'honor': [[52, 5], [51, 5], [53, 6], [54, 6]] },
            { 'type': 1, 'region': "北京赛区（北京师范大学）", 'honor': [[50, 4], [48, 5], [54, 7]] },
            { 'type': 1, 'region': "广州赛区（华南理工大学）", 'honor': [[49, 5], [55, 6]] },
            { 'type': 1, 'region': "上海赛区（上海大学）", 'honor': [[55, 6], [53, 6]] },
        ],
        "2013": [
            { 'type': 1, 'region': "成都赛区（电子科技大学）", 'honor': [[41, 5], [42, 7]] },
            { 'type': 1, 'region': "杭州赛区（浙江工业大学）", 'honor': [[43, 5], [44, 5]] },
            { 'type': 1, 'region': "南京赛区（南京理工大学）", 'honor': [[45, 4], [44, 5]] },
            { 'type': 1, 'region': "长沙赛区（湖南大学）", 'honor': [[45, 5], [46, 6], [43, 6]] },
            { 'type': 1, 'region': "长春赛区（吉林大学）", 'honor': [[47, 6], [46, 6]] },
        ],
        "2012": [
            { 'type': 0, 'region': "圣彼得堡，俄罗斯", 'honor': [[35, -27]] },
            { 'type': 1, 'region': "长春赛区（东北师范大学）", 'honor': [[35, 5], [36, 6], [37, 6]] },
            { 'type': 1, 'region': "天津赛区（天津理工大学）", 'honor': [[35, 4], [38, 5], [37, 5]] },
            { 'type': 1, 'region': "金华赛区（浙江师范大学）", 'honor': [[39, 5], [40, 6]] },
            { 'type': 1, 'region': "杭州赛区（浙江理工大学）", 'honor': [[38, 6], [36, 6]] },
            { 'type': 1, 'region': "成都赛区（成都东软学院）", 'honor': [[40, 6]] },
        ],
        "2011": [
            { 'type': 1, 'region': "大连赛区（大连理工大学）", 'honor': [[30, 5], [31, 6]] },
            { 'type': 1, 'region': "上海赛区（复旦大学）", 'honor': [[30, 5]] },
            { 'type': 1, 'region': "北京赛区（北京邮电大学）", 'honor': [[32, 6], [33, 6]] },
            { 'type': 1, 'region': "成都赛区（成都东软学院）", 'honor': [[34, 5], [31, 6]] },
            { 'type': 1, 'region': "福州赛区（福建师范大学）", 'honor': [[34, 5]] },
        ],
        "2010": [
            { 'type': 1, 'region': "哈尔滨赛区（哈尔滨工程大学）", 'honor': [[24, 7], [25, 7]] },
            { 'type': 1, 'region': "天津赛区（天津大学）", 'honor': [[26, 5], [27, 5]] },
            { 'type': 1, 'region': "杭州赛区（浙江理工大学）", 'honor': [[25, 6], [27, 7]] },
            { 'type': 1, 'region': "成都赛区（四川大学）", 'honor': [[28, 7], [29, 7]] },
            { 'type': 1, 'region': "福州赛区（福州大学）", 'honor': [[26, 5]] },
        ],
        "2009": [
            { 'type': 1, 'region': "合肥赛区（中国科学技术大学）", 'honor': [[18, 6], [19, 7]] },
            { 'type': 1, 'region': "宁波赛区（浙江大学宁波理工学院）", 'honor': [[20, 6]] },
            { 'type': 1, 'region': "上海赛区（东华大学）", 'honor': [[21, 5], [22, 5]] },
            { 'type': 1, 'region': "武汉赛区（武汉大学）", 'honor': [[18, 5], [23, 6]] },
            { 'type': 1, 'region': "哈尔滨赛区（哈尔滨工业大学）", 'honor': [[21, 5], [19, 6]] },
        ],
        "2008": [
            { 'type': 1, 'region': "哈尔滨赛区（哈尔滨工程大学）", 'honor': [[13, 5]] },
            { 'type': 1, 'region': "北京赛区（北京交通大学）", 'honor': [[14, 6], [15, 6]] },
            { 'type': 1, 'region': "合肥赛区（中国科技大学）", 'honor': [[16, 4], [17, 6]] },
            { 'type': 1, 'region': "杭州赛区（杭州电子科技大学）", 'honor': [[17, 5]] },
            { 'type': 1, 'region': "成都赛区（西南民族大学）", 'honor': [[16, 5]] },
        ],
        "2007": [
            { 'type': 1, 'region': "南京赛区（南京航空航天大学）", 'honor': [[4, 5], [5, 6], [6, 7]] },
            { 'type': 1, 'region': "长春赛区（吉林大学）", 'honor': [[7, 6], [8, 6], [9, 6]] },
            { 'type': 1, 'region': "成都赛区（西华大学）", 'honor': [[10, 5], [11, 5], [12, 5]] },
        ],
        "2006": [
            { 'type': 1, 'region': "北京赛区（清华大学）", 'honor': [[1, 4]] },
            { 'type': 1, 'region': "西安赛区（西安电子科技大学）", 'honor': [[2, 6]] },
            { 'type': 1, 'region': "上海赛区（上海大学）", 'honor': [[3, 7]] },
        ],
        "2005": [
            { 'type': 1, 'region': "北京赛区（北京大学）", 'honor': [[0, 6]] },
        ],
    }

    members = [
        {'name': "刘其帅", 'major': ""},
        {'name': "焦航", 'major': ""},
        {'name': "李子星", 'major': ""},
        {'name': "刘永罡", 'major': ""},
        {'name': "常达", 'major': ""},
        {'name': "逄望舒", 'major': ""},
        {'name': "赵洋磊", 'major': ""},
        {'name': "李宇杰", 'major': ""},
        {'name': "徐俣", 'major': ""},
        {'name': "宋恒", 'major': ""},
        {'name': "赖景愚", 'major': ""},
        {'name': "李论", 'major': ""},
        {'name': "王珂龙", 'major': ""},
        {'name': "方志文", 'major': ""},
        {'name': "谢舒翼", 'major': ""},
        {'name': "郭浩泉", 'major': ""},
        {'name': "任斐", 'major': ""},
        {'name': "盛斌", 'major': ""},
        {'name': "张嘉琳", 'major': ""},
        {'name': "乔衎", 'major': ""},
        {'name': "邹佳辰", 'major': ""},
        {'name': "邓梁栋", 'major': ""},
        {'name': "王冉", 'major': ""},
        {'name': "孙睿", 'major': ""},
        {'name': "崔超", 'major': ""},
        {'name': "郭信谊", 'major': ""},
        {'name': "刘建云", 'major': ""},
        {'name': "关育新", 'major': ""},
        {'name': "闫晟东", 'major': ""},
        {'name': "洪婉玲", 'major': ""},
        {'name': "王跃", 'major': ""},
        {'name': "陈嘉晖", 'major': ""},
        {'name': "谢科", 'major': ""},
        {'name': "管清文", 'major': ""},
        {'name': "杨晓", 'major': ""},
        {'name': "叶博", 'major': ""},
        {'name': "李明康", 'major': ""},
        {'name': "曾立", 'major': ""},
        {'name': "杨博洋", 'major': ""},
        {'name': "郭子晨", 'major': ""},
        {'name': "王晓宇", 'major': ""},
        {'name': "倪亦帅", 'major': ""},
        {'name': "柳奇涛", 'major': ""},
        {'name': "于野", 'major': ""},
        {'name': "阎骥洲", 'major': ""},
        {'name': "吴昊天", 'major': ""},
        {'name': "章烨钦", 'major': ""},
        {'name': "邓宣颖", 'major': ""},
        {'name': "高维", 'major': ""},
        {'name': "刘维同", 'major': ""},
        {'name': "孙萌", 'major': ""},
        {'name': "简讯", 'major': ""},
        {'name': "彭龙", 'major': ""},
        {'name': "董适", 'major': ""},
        {'name': "肖文聪", 'major': ""},
        {'name': "王安然", 'major': ""},
        {'name': "刘思学", 'major': ""},
        {'name': "卢超", 'major': ""},
        {'name': "朱耿良", 'major': ""},
        {'name': "李鑫慧", 'major': ""},
        {'name': "鲁海浩", 'major': ""},
        {'name': "姜睿昶", 'major': ""},
        {'name': "谭传奇", 'major': ""},
        {'name': "栾贝迪", 'major': ""},
        {'name': "夏正林", 'major': ""},
        {'name': "袁政", 'major': ""},
        {'name': "黎健成", 'major': ""},
        {'name': "杨思宇", 'major': ""},
        {'name': "周帅", 'major': ""},
        {'name': "李业树", 'major': ""},
        {'name': "余铠", 'major': ""},
        {'name': "陈志兴", 'major': ""},
        {'name': "王剑锋", 'major': ""},
        {'name': "李森栋", 'major': ""},
        {'name': "？", 'major': ""},
        {'name': "刘毅博", 'major': ""},
        {'name': "李珎", 'major': ""},
        {'name': "梁明阳", 'major': ""},
        {'name': "徐少峰", 'major': ""},
        {'name': "赵轩昂", 'major': ""},
        {'name': "李炎", 'major': ""},
        {'name': "王昌宝", 'major': ""},
        {'name': "李明星", 'major': ""},
        {'name': "孟春雷", 'major': ""},
        {'name': "董宣毅", 'major': ""},
        {'name': "金胜莺", 'major': ""},
        {'name': "赵海宇", 'major': ""},
        {'name': "赵东方", 'major': ""},
        {'name': "李周洋", 'major': ""},
        {'name': "李睿霖", 'major': ""},
        {'name': "刘垚鹏", 'major': ""},
        {'name': "骈扬", 'major': ""},
        {'name': "董舒印", 'major': ""},
        {'name': "付成真", 'major': ""},
        {'name': "朱峰达", 'major': ""},
        {'name': "林泉沛", 'major': ""},
        {'name': "李沛伦", 'major': ""},
        {'name': "张沛", 'major': ""},
        {'name': "唐靖哲", 'major': ""},
        {'name': "邓博洋", 'major': ""},
        {'name': "田茂清", 'major': ""},
        {'name': "张奥", 'major': ""},
        {'name': "刘保证", 'major': ""},
        {'name': "何玥", 'major': ""},
        {'name': "冯炜韬", 'major': ""},
        {'name': "杨子琛", 'major': ""},
        {'name': "黄鑫", 'major': ""},
        {'name': "李奕君", 'major': ""},
        {'name': "史雨轩", 'major': ""},
        {'name': "李晨豪", 'major': ""},
        {'name': "户建坤", 'major': ""},
        {'name': "史烨轩", 'major': ""},
        {'name': "林子义", 'major': ""},
        {'name': "黄宏鸣", 'major': ""},
        {'name': "李搏", 'major': ""},
        {'name': "刘子渊", 'major': ""},
        {'name': "钟金成", 'major': ""},
        {'name': "胡智昊", 'major': ""},
        {'name': "蒋泳波", 'major': ""},
        {'name': "高威", 'major': ""},
        {'name': "朱福", 'major': ""},
        {'name': "张乾宇", 'major': ""},
        {'name': "张明远", 'major': ""},
        {'name': "贺牧天", 'major': ""},
        {'name': "金代圣", 'major': ""},
        {'name': "朱瑾", 'major': ""},
        {'name': "谢瑶瑶", 'major': ""},
        {'name': "李何贝子", 'major': ""},
        {'name': "王柏润", 'major': ""},
        {'name': "伍俊洁", 'major': ""},
        {'name': "钟梓皓", 'major': ""},
        {'name': "邓一兴", 'major': ""},
        {'name': "黄浩东", 'major': ""},
        {'name': "张少昂", 'major': ""},
        {'name': "姜圣虎", 'major': ""},
        {'name': "沈中海", 'major': ""},
        {'name': "杜昊", 'major': ""},
        {'name': "赵立晨", 'major': ""},
        {'name': "王嘉翼", 'major': ""},
        {'name': "周环宇", 'major': ""},
        {'name': "何铭睿", 'major': ""},
        {'name': "向宏毅", 'major': ""},
        {'name': "郭镕昊", 'major': ""},
        {'name': "王意如", 'major': ""},
        {'name': "彭毛小民", 'major': ""},
        {'name': "张凯杰", 'major': ""},
        {'name': "郑耀彦", 'major': ""},
        {'name': "肖思炀", 'major': ""},
        {'name': "丁元杰", 'major': ""},
        {'name': "廖纪童", 'major': ""},
        {'name': "杨开元", 'major': ""},
        {'name': "林昱同", 'major': ""},
        {'name': "陈铭煊", 'major': ""},
        {'name': "龙鹏宇", 'major': ""},
        {'name': "阙子烝", 'major': ""},
        {'name': "孙保成", 'major': ""},
        {'name': "邹增禹", 'major': ""},
        {'name': "王廉杰", 'major': ""},
        {'name': "牟钰", 'major': ""},
        {'name': "冯玮琪", 'major': ""},
        {'name': "马广林", 'major': ""},
        {'name': "李元恺", 'major': ""},
        {'name': "袁熙", 'major': ""},
        {'name': "姜维翰", 'major': ""},
        {'name': "康时嘉", 'major': ""},
        {'name': "田柯宇", 'major': ""},
        {'name': "周海涛", 'major': ""},
        {'name': "赵婉如", 'major': ""},
        {'name': "黄云依", 'major': ""},
        {'name': "常荣熇", 'major': ""},
    ]

    for year, contests in regions.items():
        for contest in contests:
            for honor in contest['honor']:
                team_id = honor[0]
                teams[team_id]['year'] = year
    for id, team in enumerate(teams):
        if id in [94, 101]:
            print(team)
            continue

        # data = {
        #     'name': team['cn'],
        #     'english_name': team['en'],
        #     'year': team['year'],
        #     'member1': members[team['members'][0]]['name'],
        #     'member2': members[team['members'][1]]['name'],
        #     'member3': members[team['members'][2]]['name'],
        # }
        # print(data)
        # r = session.patch(f'http://127.0.0.1:8000/team/add_members/', data=data)
        # print(r.text)
